version: "3.8"

services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - core-service
      - code-manager-service
      - chatbot-service
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_HEARTBEAT: 3600
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network

  core-service:
    build: ./services/core
    ports:
      - "8001:8001"
    volumes:
      - ./services/core:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network
    environment:
      - MONGO_URL=mongodb://core:12345678@mongo:27017/core-database?authSource=core-database

  code-manager-service:
    build: ./services/code_manager
    volumes:
      - ./services/code_manager:/app
    ports:
      - "8002:8002"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network
    environment:
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672/
      - MONGO_URL=mongodb://root:password@mongo:27017

  code-execute-worker-service:
    build: ./services/code_execute_worker
    volumes:
      - ./services/code_execute_worker:/app
      - /tmp/code_manager:/tmp/code_manager:rw
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8012:8012"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672/

  chatbot-service:
    build: ./services/chatbot
    ports:
      - "8003:8003"
    networks:
      - app-network
    environment:
      - MONGO_URL=mongodb://root:password@mongo:27017

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
