version: '3.8'

services:
  nginx:
    build: ./ngix
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - user-service
      - code-manager-service
      - chatbot-service
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app-network

  user-service:
    build: ./services/user
    ports:
      - "8001:8001"
    networks:
      - app-network

  code-manager-service:
    build: ./services/code_manager
    volumes:
      - ./services/code_manager:/app
      # - ./services/code_manager/tmp:/usr/src/app:rw
      - /tmp/code_manager:/tmp/code_manager:rw
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8002:8002"
    networks:
      - app-network
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock

  chatbot-service:
    build: ./services/chatbot
    ports:
      - "8003:8003"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
