version: "3.8"

services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - core-service
      - code-manager-service
      - chatbot-service
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_HEARTBEAT: 3600
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:latest
    container_name: mongo
    command:
      ["--replSet", "rs0", "--bind_ip_all", "--keyFile", "/etc/mongo-keyfile"]
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongo-keyfile:/etc/mongo-keyfile
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - app-network

  mongo-init:
    image: mongo:latest
    container_name: mongo-init
    restart: "no"
    depends_on:
      - mongo
    command: >
      bash -c "
        echo 'Waiting for MongoDB to start...'
        sleep 10
        mongosh --host mongo:27017 -u root -p password --authenticationDatabase admin --eval '
          rs.initiate({
            _id: \"rs0\",
            members: [{ _id: 0, host: \"mongo:27017\" }]
          });
          db = db.getSiblingDB(\"core-database\");
          db.createUser({
            user: \"core\",
            pwd: \"12345678\",
            roles: [{ role: \"readWrite\", db: \"core-database\" }]
          });
        '
        echo 'MongoDB Replica Set initialized'
      "
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network
    volumes:
      - redis-data:/data
    command: redis-server --save 60 1 --loglevel warning
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    privileged: true

  core-service:
    build: ./services/core
    ports:
      - "8001:8001"
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./services/core:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network
    environment:
      - MONGO_URL=mongodb://core:12345678@mongo:27017/core-database?authSource=core-database&replicaSet=rs0
      - REDIS_URL=redis://redis:6379

  code-manager-service:
    build: ./services/code_manager
    volumes:
      - ./services/code_manager:/app
    ports:
      - "8002:8002"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network
    environment:
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672/
      - MONGO_URL=mongodb://root:password@mongo:27017/?replicaSet=rs0

  code-execute-worker-service:
    build: ./services/code_execute_worker
    volumes:
      - ./services/code_execute_worker:/app
      - /tmp/code_manager:/tmp/code_manager:rw
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8012:8012"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672/

  chatbot-service:
    build: ./services/chatbot
    ports:
      - "8003:8003"
    networks:
      - app-network
    environment:
      - MONGO_URL=mongodb://root:password@mongo:27017/?replicaSet=rs0

volumes:
  mongo-data:
  redis-data:

networks:
  app-network:
    driver: bridge
